version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn install
      - mvn package

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: maven-web-application 0.0.1-SNAPSHOT.war
